// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Album struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Year     int    `json:"year"`
	Artist   string `json:"artist"`
	Genre    string `json:"genre"`
	Uploader *User  `json:"uploader"`
}

type AlbumSearch struct {
	Name   string `json:"name"`
	Artist string `json:"artist"`
}

type NewAlbum struct {
	Name   string `json:"name"`
	Artist string `json:"artist"`
	Genre  string `json:"genre"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}
