CREATE TABLE IF NOT EXISTS Polls(
  ID INT NOT NULL UNIQUE AUTO_INCREMENT,
  Name VARCHAR (127) NOT NULL,
  CreatorID INT,
  FOREIGN KEY (CreatorID) REFERENCES Users(Id),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS Poll_Album(
  ID INT NOT NULL UNIQUE AUTO_INCREMENT,
  AlbumID INT,
  PollID INT,
  FOREIGN KEY (AlbumID) REFERENCES Albums(ID),
  FOREIGN KEY (PollID) REFERENCES Polls(ID),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS Votes(
  ID INT NOT NULL UNIQUE AUTO_INCREMENT,
  AlbumID INT,
  PollID INT,
  VoterID INT,
  FOREIGN KEY (AlbumID) REFERENCES Albums(ID),
  FOREIGN KEY (PollID) REFERENCES Polls(ID),
  FOREIGN KEY (VoterID) REFERENCES Users(ID),
  PRIMARY KEY (ID)
);